---
title: "SARS-CoV-2 Comparison"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Libraries

```{r message=FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
options(width=5000)
```
## Read the Data and Preprocess

First, read the data from the TSV file and do the preprocessing.

```{r}
data <- read.csv(file='dataset/GSE147507_RawReadCounts.tsv', header=TRUE, sep="\t")
colnames(data)[1] <- 'gene'
colnames(data)[2] <- 'healthy_1'
colnames(data)[3] <- 'healthy_2'
colnames(data)[4] <- 'healthy_3'
colnames(data)[5] <- 'sarscov2_1'
colnames(data)[6] <- 'sarscov2_2'
colnames(data)[7] <- 'sarscov2_3'
colnames(data)[8] <- 'healthy_4'
colnames(data)[9] <- 'healthy_5'
colnames(data)[10] <- 'healthy_6'
colnames(data)[11] <- 'sarscov2_4'
colnames(data)[12] <- 'sarscov2_5'
colnames(data)[13] <- 'sarscov2_6'
data <- data %>% mutate(gene_id=rownames(data))
data <- data %>% select(gene_id, gene, healthy_1, healthy_2, healthy_3, sarscov2_1, sarscov2_2, sarscov2_3, healthy_4, healthy_5, healthy_6, sarscov2_4, sarscov2_5, sarscov2_6)

# Apply log transformation
epsilon <- 1 # constant value to avoid undefined in the case of 0.
data <- data %>% 
  mutate(healthy_1 = log(healthy_1 + epsilon),
         healthy_2 = log(healthy_2 + epsilon),
         healthy_3 = log(healthy_3 + epsilon),
         healthy_4 = log(healthy_4 + epsilon),
         healthy_5 = log(healthy_5 + epsilon),
         healthy_6 = log(healthy_6 + epsilon),
         sarscov2_1 = log(sarscov2_1 + epsilon),
         sarscov2_2 = log(sarscov2_2 + epsilon),
         sarscov2_3 = log(sarscov2_3 + epsilon),
         sarscov2_4 = log(sarscov2_4 + epsilon),
         sarscov2_5 = log(sarscov2_5 + epsilon),
         sarscov2_6 = log(sarscov2_6 + epsilon))

# Compute the standard deviations
data <- data %>%
  rowwise() %>%
  mutate(sd_healthy_1 = sd(c(healthy_1, healthy_2, healthy_3)),
         sd_infected_1 = sd(c(sarscov2_1, sarscov2_2, sarscov2_3)),
         sd_healthy_2 = sd(c(healthy_4, healthy_5, healthy_6)),
         sd_infected_2 = sd(c(sarscov2_4, sarscov2_5, sarscov2_6))) %>%
  ungroup()

# Compute the means
data <- data %>%
  rowwise() %>%
  mutate(mean_healthy_1 = mean(c(healthy_1, healthy_2, healthy_3)),
         mean_infected_1 = mean(c(sarscov2_1, sarscov2_2, sarscov2_3)),
         mean_healthy_2 = mean(c(healthy_4, healthy_5, healthy_6)),
         mean_infected_2 = mean(c(sarscov2_4, sarscov2_5, sarscov2_6))) %>%
  ungroup()

# Compute the p-value
ttest <- function (x, y) {
  if (identical(x, y) | min(y-x) == max(y-x)) {
    return(1)
  }
  res <- t.test(x, y)
  return(res$p.value)
}
data <- data %>%
  rowwise() %>%
  mutate(p_1=ttest(c(healthy_1, healthy_2, healthy_3), c(sarscov2_1, sarscov2_2, sarscov2_3)),
         p_2=ttest(c(healthy_4, healthy_5, healthy_6), c(sarscov2_4, sarscov2_5, sarscov2_6))) %>%
  ungroup()

alpha <- 0.05
data <- data %>%
  mutate(significant_1 = ifelse(p_1 < alpha, 'yes', 'no'),
         significant_2 = ifelse(p_2 < alpha, 'yes', 'no'))
data <- data %>%
  mutate(significance = ifelse(significant_1 == 'yes' & significant_2 == 'yes', 'both',
                        ifelse(significant_1 == 'yes', 'Cell 1 only',
                        ifelse(significant_2 == 'yes', 'Cell 2 only', 'no'))))
```

## Distribution of Standard Deviation within Healthy and Infected Cells
```{r echo=FALSE, warning=FALSE}
sd_healthy_1 <- data$sd_healthy_1 %>% unlist()
sd_healthy_2 <- data$sd_healthy_2 %>% unlist()
sd_infected_1 <- data$sd_infected_1 %>% unlist()
sd_infected_2 <- data$sd_infected_2 %>% unlist()
sdtable <- data.frame(sd = sd_healthy_1, type = rep('healthy', nrow(data)), cell = rep('Cell Type 1', nrow(data))) %>%
  rbind(data.frame(sd = sd_healthy_2, type = rep('healthy', nrow(data)), cell = rep('Cell Type 2', nrow(data)))) %>%
  rbind(data.frame(sd = sd_infected_1, type = rep('infected', nrow(data)), cell = rep('Cell Type 1', nrow(data)))) %>%
  rbind(data.frame(sd = sd_infected_2, type = rep('infected', nrow(data)), cell = rep('Cell Type 2', nrow(data))))
sdtable <- sdtable %>% filter(sd != 0)
ggplot(data=sdtable, aes(x=sd, fill=type)) + 
  geom_histogram(position='identity', binwidth=0.1, alpha=0.5) + 
  scale_y_continuous(limits=c(-0,8000)) +
  scale_x_continuous(limits=c(-0.1,2)) +
  xlab("Standard Deviation") + ggtitle("Std. Dev. Distribution") +
  facet_wrap(~cell, nrow=2, ncol=1)
```

## Difference of Means Between Healthy and Infected Cells

```{r echo=FALSE, warning=FALSE}
diff_1 <- data$mean_healthy_1 - data$mean_infected_1 %>% unlist()
diff_2 <- data$mean_healthy_2 - data$mean_infected_2 %>% unlist()
difftable <- data.frame(diff=diff_1, cell=rep('Cell Type 1', nrow(data))) %>%
  rbind(data.frame(diff=diff_2, cell=rep('Cell Type 2', nrow(data))))
ggplot(data=difftable, aes(x=diff, fill=cell)) +
  geom_histogram(binwidth=0.2, position='identity', alpha=0.5) +
  scale_fill_manual(values=c('darkgreen', 'yellow')) +
  scale_x_continuous(limit=c(-4,2)) +
  xlab('difference in mean (< 0 means infected is more)') +
  ggtitle('Distribution of Difference in Means (healthy - infected)')
```

## Which Genes Have High Discrepancies Between Healthy and Infected Cells?

```{r echo=FALSE, warning=FALSE}
n <- nrow(data)
lower_1 <- data %>% arrange(mean_healthy_1 - mean_infected_1) %>% head(n=n)
upper_1 <- data %>% arrange(desc(mean_healthy_1 - mean_infected_1)) %>% head(n=n)
lower_2 <- data %>% arrange(mean_healthy_2 - mean_infected_2) %>% head(n=n)
upper_2 <- data %>% arrange(desc(mean_healthy_2 - mean_infected_2)) %>% head(n=n)
top_gene_ids <- c(lower_1$gene_id, lower_2$gene_id, upper_1$gene_id, upper_2$gene_id) %>% unique() 
data.trimmed <- data %>% filter(gene_id %in% top_gene_ids)
ggplotly(
  ggplot(data=data.trimmed,
  aes(x=mean_healthy_1 - mean_infected_1, y = mean_healthy_2 - mean_infected_2,  label=gene, color=significance)) +
  xlab("Cell Type 1 difference (< 0 means infected is more)") +
  ylab("Cell Type 2 difference (< 0 means infected is more)") +
  ggtitle("Differences for Each Gene") +
geom_point() +
scale_color_manual(values=c('green', 'darkgreen', 'yellow', 'gray')) +
geom_hline(yintercept=0, color='red') +
geom_vline(xintercept=0, color='red')
)
```

```{r echo=FALSE, warning=FALSE}
n <- nrow(data)
lower_1 <- data %>% arrange(mean_healthy_1 - mean_infected_1) %>% head(n=n)
upper_1 <- data %>% arrange(desc(mean_healthy_1 - mean_infected_1)) %>% head(n=n)
lower_2 <- data %>% arrange(mean_healthy_2 - mean_infected_2) %>% head(n=n)
upper_2 <- data %>% arrange(desc(mean_healthy_2 - mean_infected_2)) %>% head(n=n)
top_gene_ids <- c(lower_1$gene_id, lower_2$gene_id, upper_1$gene_id, upper_2$gene_id) %>% unique() 
data.trimmed <- data %>% filter(gene_id %in% top_gene_ids) %>% filter(significance != 'no')
ggplotly(
  ggplot(data=data.trimmed,
  aes(x=mean_healthy_1 - mean_infected_1, y = mean_healthy_2 - mean_infected_2,  label=gene, color=significance)) +
  xlab("Cell Type 1 difference (< 0 means infected is more)") +
  ylab("Cell Type 2 difference (< 0 means infected is more)") +
  ggtitle("Differences for Each Gene") +
geom_point() +
scale_color_manual(values=c('green', 'darkgreen', 'yellow', 'gray')) +
geom_hline(yintercept=0, color='red') +
geom_vline(xintercept=0, color='red')
)
```